// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRh1_r_QHJRSimZyqoyt0R0KczS6o4EqA',
    appId: '1:650287532804:web:86a39df81f3fe31f42de51',
    messagingSenderId: '650287532804',
    projectId: 'leave-5a013',
    authDomain: 'leave-5a013.firebaseapp.com',
    storageBucket: 'leave-5a013.firebasestorage.app',
    measurementId: 'G-5P207V2RHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6ePkH-t-JsiiS2SoXLk7yYovVHThW4M',
    appId: '1:650287532804:android:03b6e7c05ff42bdd42de51',
    messagingSenderId: '650287532804',
    projectId: 'leave-5a013',
    storageBucket: 'leave-5a013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPstN6kAHsXPZ4NffWSMAOfDkNRgz_tBk',
    appId: '1:650287532804:ios:599b6b09a09dea0542de51',
    messagingSenderId: '650287532804',
    projectId: 'leave-5a013',
    storageBucket: 'leave-5a013.firebasestorage.app',
    iosBundleId: 'com.example.yoyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPstN6kAHsXPZ4NffWSMAOfDkNRgz_tBk',
    appId: '1:650287532804:ios:599b6b09a09dea0542de51',
    messagingSenderId: '650287532804',
    projectId: 'leave-5a013',
    storageBucket: 'leave-5a013.firebasestorage.app',
    iosBundleId: 'com.example.yoyo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRh1_r_QHJRSimZyqoyt0R0KczS6o4EqA',
    appId: '1:650287532804:web:e65a1db8204cb56542de51',
    messagingSenderId: '650287532804',
    projectId: 'leave-5a013',
    authDomain: 'leave-5a013.firebaseapp.com',
    storageBucket: 'leave-5a013.firebasestorage.app',
    measurementId: 'G-MLP2Q9NZR6',
  );
}
